- review/input_source_precessing.py
> Implement feature/get_info_img functionality

- review/ai_module.py
- review/views.py
add ai_module.py , 그리고 리뷰, 재리뷰 ai 모델들을 모듈로 정리해서 완료함.
> feature/ai_modules.py 

- review/urls.py
- review/views.py
> code merged & api들 다 구현

- review/ai_module.py
> Refactor: Rename chatbot_service to generate_chatbot for consistency

- review/ai_module.py
- review/views.py
- Added chatbot feature to views.py to handle user queries
- Updated generate_chatbot function in ai_modules.py for better response accuracy
- Enhanced error handling for chatbot API requests
> Feat: Integrate chatbot into API and improve chatbot response generation

- review/models.py
같은 문제 아이디를 공유하는 히스토리에 대해선 같은 솔루션 코드를 제공하도록 모델을 수정했습니다.
review/models.py
solution.history_id -> solution.problem_id
> 솔루션 코드 통합 기능

- review/urls.py
- review/views.py
- Implemented get_solution and create_solution in review/views.py
- Added get_object_or_404 for safer object retrieval
- Updated review/urls.py to remove redundant API paths
- Registered get_solution and create_solution routes
- Improved overall API structure for solution management
> Feat: Add solution retrieval and creation API endpoints

- review/ai_module.py
"ai_module.py"에서 리뷰에 final_list에 False 추가, 재리뷰 전체적으로 새로 재작성하고, 리뷰 함수도 약간 수정하였다.
> "ai_module.py"에서 리뷰에 final_list에 False 추가, 재리뷰 전체적으로 새로 재작성

- review/ai_module.py
최초리뷰_정규표현식 오류
- 정규표현식을 옛날 방식을 사용
> 최초리뷰_정규표현식 오류

- review/ai_module.py
SOLUTION_CODE START_LINE_NUMBER, END_LINE_NUMBER 수정
> SOLUTION_CODE START_LINE_NUMBER, END_LINE_NUMBER 수정

- review/views.py
모범 답안 생성 및 조회 API의 로직을 변경했습니다. (FE와 협의)
> refactor(solution): update API spec based on FE requirements

- review/ai_module.py
code_response = code_response.strip().strip("```")
def_index = code_response.find("def")
if def_index != -1:
code_response = code_response[def_index:]
code_response = code_response.strip().strip("```").strip()
문구 추가함. 이 언어가 python인지 java인지 어떤 언어인지 모르기 때문에
> soluton ''' ''' 그리고 어떤 언어인지 빼는거 올림

- review/views.py
리뷰 생성 로직 변경
- problem_info를 추출하는 조건문에서 필요한 데이터 조회를 하도록 변경
- input_souce, input_data 데이터 접근을 if문 안으로 배정
- 처음 POST 요청에서 undefined에 의한 데이터 접근 keyError 발생을 해결
> Refactor(review): Improve POST handler logic for /api/v1/review

- review/ai_module.py
pass한 경우에도 해결한 부분에 대한 시작줄, 끝줄을 출력하는 success한 line 위치를 출력
> pass한 경우에도 해결한 부분에 대한 시작줄, 끝줄을 출력하는 success한 line 위치를 출력

- review/models.py
- review/views.py
feat: SolutionLine 모델 추가 및 solution API 엔드포인트 수정
- 문제 해답 저장을 위한 SolutionLine 모델 추가
- Swagger 명세에 맞춰 solution API 엔드포인트 수정:
- GET /api/v1/solution/{problem_id}
- POST /api/v1/solution/{problem_id}
Swagger에 문서화된 API 명세를 기준으로 구현했습니다!
> Feat: Add SolutionLine model and update solution API endpoints

- review/urls.py
- review/views.py
로직 수정: review 요청 데이터에 history_name, problem_name 추가
> Refactor: Add history_name and problem_name to review request data

- review/ai_module.py
generate_solution_code에서 solution_code 출력하고, 또한 title,start_line, end_line 으로 해서 3개를 묶은 [title,start_line,end_line] 묶은 리스트인 solution_list도 리턴하는 함수를 만들었습니다.
> "ai_module.py" 에 generate_solution_code 함수 총체적으로 수정

- review/ai_module.py
feedback_prompt 구체화, 리뷰,solution 출력물에 대한 파싱함수 수정
> feedback_prompt 구체화, 리뷰,solution 출력물에 대한 파싱함수 수정

- review/ai_module.py
solution_code에 백틱(''')언어 ''' 하는 부분 삭제, 한줄을 삭제
=> 첫줄을 삭제했으므로 start_line과 end_line 에 각각 -1 하는 코드 추가
code_match = re.search(r"^(.*?)(?=\n<lines>)", code_response, re.DOTALL)
markdown_code = code_match.group(1).strip() if code_match else "No Code Found"
middle_lines = markdown_code.splitlines()
solution_lines = middle_lines[1:-1]
solution_code = "\n".join(solution_lines)
xml_match = re.search(r"<lines>(.*?)</lines>", code_response, re.DOTALL)
solution_xml = f"<lines>{xml_match.group(1)}</lines>" if xml_match else "No Lines Found"
solution_list = []
if "No Lines Found" not in solution_xml:  # XML 데이터가 존재하는 경우만 처리
root = ET.fromstring(solution_xml)
for line in root.findall(".//line"):
title = line.find("title").text
start_line = int(line.find("start_line").text) - 1
end_line = …
> solution_code에 백틱(''')언어 ''' 하는 부분 삭제, 한줄을 삭제

- backend/settings.py
Feat: Django 정적 파일 설정 구성
- 정적 파일 서빙 경로를 위한 STATIC_URL 설정 추가
- collectstatic 디렉토리 지정을 위한 STATIC_ROOT 설정 추가
- 프로덕션 환경에서 정적 파일 처리 활성화
- 의미없는 디렉토리 제거 (backend_yoon)
> Feat: Configure Django static files settings

- review/views.py
히스토리 이름을 revision 기반으로 '{revision}번째 리뷰'로 설정
> Feat: set history name based on revision as '{revision}th review'

- review/ai_module.py
- review/input_source_precessing.py
get_info_img 프로세스 개선
- 프로덕션 환경에서 Django settings를 통해 GENAI_API_KEY 불러오도록 수정
> Refactor: get_info_img process

- review/ai_module.py
lines prompt 성능 향상 시켰습니다
- reviews , re_reviews 함수에 적용되는 코드도 수정
> lines prompt 성능 향상

- review/input_source_precessing.py
**이미지 처리 프로세스 개선**
- base64 모듈 추가하여 인코딩된 바이너리 파일 디코딩 구현
- io 모듈을 활용한 이미지 파일 처리 로직 추가
- 두 번 인코딩된 base64 바이너리 파일 문자열 올바르게 처리
> Fix(get_info_img): Improve image processing flow
